### ISSUE TITLE
Conda package is broken for Linux/Python 3.8 and 3.9

### ISSUE THREAD

**Issue by bwohlberg** [PyAbel/PyAbel#320]
On Ubuntu 20.04.2 with Python 3.8.10, after installing via conda
```
The following NEW packages will be INSTALLED:

  pyabel             conda-forge/linux-64::pyabel-0.8.3-py38h8790de6_0
```
any attempt to import the `abel` module leads to a core dump with error
```
Illegal instruction (core dumped)
```

**Comment by DanHickstein** [comment]
It is just the conda-forge package? Does the pip install work fine?

**Comment by MikhailRyazanov** [comment]
The zeroth question would be: who releases the conda-forge packages and why is it still v0.8.3, while our v0.8.4 has been released more than 2 months ago (and became available on PyPI at the same time)?

**Comment by bwohlberg** [comment]
> It is just the conda-forge package? Does the pip install work fine?

Yes, the version from PyPI seems fine.

**Comment by bwohlberg** [comment]
> The zeroth question would be: who releases the conda-forge packages and why is it still v0.8.3, while our v0.8.4 has been released more than 2 months ago (and became available on PyPI at the same time)?

You can see who is involved in maintaining the conda-forge package [here](https://github.com/conda-forge/pyabel-feedstock). It's not obvious why it hasn't been updated to match the most recent package release.

**Comment by MikhailRyazanov** [comment]
The README file there lists our members as “Feedstock Maintainers”, but the last commit from them (@rth) to that repository is from 2018, and mostly other people and bots took care of it. So maybe it would help to ask _there_ what's going on?

**Comment by bwohlberg** [comment]
The feedstock maintainers should all have access to update the conda packaging, so I would suggest contacting them about this.

**Comment by rth** [comment]
Interesting I can reproduce,

Here is the backtrace
<details>


```
Thread 1 "python" received signal SIGILL, Illegal instruction.                                     
0x00007fffd21d84b2 in __pyx_pymod_exec_direct ()                                                   
   from /home/rth/miniconda3/envs/test-env2/lib/python3.8/site-packages/abel/lib/direct.cpython-38-
x86_64-linux-gnu.so                                                                                
(gdb) bt                                                                                           
#0  0x00007fffd21d84b2 in __pyx_pymod_exec_direct ()                                               
   from /home/rth/miniconda3/envs/test-env2/lib/python3.8/site-packages/abel/lib/direct.cpython-38-
x86_64-linux-gnu.so
#1  0x0000555555782328 in PyModule_ExecDef (module=0x7fffd2208130, def=<optimized out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Objects/moduleobj
ect.c:414
#2  0x00005555557823c3 in exec_builtin_or_dynamic (mod=0x7fffd2208130)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/import.c:2
169
#3  _imp_exec_builtin_impl (module=<optimized out>, mod=0x7fffd2208130)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/import.c:2
262
#4  _imp_exec_builtin (module=<optimized out>, mod=0x7fffd2208130)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/clinic/imp
ort.c.h:388
#5  0x00005555556789ab in cfunction_vectorcall_O (func=func@entry=0x7ffff7668590, 
    args=<optimized out>, nargsf=nargsf@entry=1, kwnames=<optimized out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Objects/methodobj
ect.c:482
#6  0x000055555568381e in PyVectorcall_Call (callable=0x7ffff7668590, tuple=<optimized out>, 
    kwargs=<optimized out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Objects/call.c:20
0
#7  0x00005555557292da in do_call_core (kwdict=0x7fffd2205500, callargs=0x7fffd22045e0, 
    func=0x7ffff7668590, tstate=<optimized out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/ceval.c:49
83
#8  _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/ceval.c:35
59
```
</details>

not sure what's causing it. Will try to update the repo to latest conda-forge recommendations, maybe something was wrong with build dependencies.

> who releases the conda-forge packages and why is it still v0.8.3, while our v0.8.4 has been released more than 2 months ago (and became available on PyPI at the same time)?

Yes, @MikhailRyazanov  feel free to add yourself to https://github.com/conda-forge/pyabel-feedstock/blob/56fa1ec17bde2699ef33918e5f560cd94e17d9e6/recipe/meta.yaml#L55  It's mostly automated so one only need to merge PRs that get opened after the PyPi release (in this case https://github.com/conda-forge/pyabel-feedstock/pull/16).

**Comment by rth** [comment]
I released 0.8.4 on conda-forge, but it's still broken on Linux. I think issue is the `-march=native` flag in `setup.py` https://github.com/PyAbel/PyAbel/blob/39501dc371c31e2660c47a1549a1cf13d60c19d3/setup.py#L41-L42

The VM where those packages are built for conda-forge apparently has a CPU with a larger instruction set than most users. Removing that flag for the next release should fix it I think.

**Comment by MikhailRyazanov** [comment]
@rth, thanks for looking into this!

> I think issue is the `-march=native` flag

Makes sense. :–) It would be strange to expect that build-server's “native” is native for everybody...

But can this be somehow modified locally in conda-forge recipes instead of removing from `PyAbel/setup.py` (because it in principle should be useful for user's local installations)?

> feel free to add yourself

I'm not using conda and don't know how it works, so for now I'd prefer to leave the responsibility to those who are more experienced. :–)

**Comment by rth** [comment]
> modified locally in conda-forge recipes

One solution could be to patch, but that's a bit discouraged. Another one could be to define some env variable that would allow to disable that flag.

**Comment by MikhailRyazanov** [comment]
In principle, in the C/C++ world, people use [`CFLAGS`](https://en.wikipedia.org/wiki/CFLAGS) and `LDFLAGS`, which can be taken from the environment and/or set in the makefile. I guess, we can do a similar thing here. Does the conda-forge building system already define something like that?

**Comment by oobie2142** [comment]
@rth 

I did try and use Python 3.5 and installed the PyAbel version that was automatically installed through conda and it worked on Linux Mint 20.2

I can try other versions once I get back to my Linux box at home just to test.

**Comment by MikhailRyazanov** [comment]
Copying @oobie2142's report from #329 here for reference:
> On Linux Mint 20.2 with Python 3.9.7 trying to import package
`33908 illegal hardware instruction (core dumped) python -c 'import IPython; IPython.terminal.ipapp.launch_new_instance()'`
Not sure if the Python 3.8 work around applies to this situation, but will I need to update some flags to get this to work?

Could you please also tell your CPU model, just in case? (Although I don't know how to find out the target CPU for a Conda package...)

Regarding workarounds, I guess that if after installing the package you manually delete the .so file from the `abel/lib` subdirectory, this will prevent PyAbel from using the Cython version of the "direct" method, but everything else should work fine.

**Comment by oobie2142** [comment]
My CPU is a Ryzen Threadripper 2920x. 

I will give that a shot.

**Comment by oobie2142** [comment]
I tried a new environment with Python 3.8.12 and was able to install and import pyabel 0.8.4

Thought I would give an update.

**Comment by MikhailRyazanov** [comment]
> Ryzen Threadripper 2920x

OK, makes sense. I've tried to disassemble the compiled library, and it shows [AVX-512](https://en.wikipedia.org/wiki/AVX-512) instructions:
```
$ objdump -d direct.cpython-39-x86_64-linux-gnu.so | grep zmm
    833a:       62 f1 fe 48 6f 1a       vmovdqu64 (%rdx),%zmm3
    8340:       62 f1 fe 48 7f 9b 50    vmovdqu64 %zmm3,0x50(%rbx)
    839b:       62 d1 fe 48 6f 10       vmovdqu64 (%r8),%zmm2
    83a1:       62 f2 fd 48 7c ca       vpbroadcastq %rdx,%zmm1
    83ab:       62 f3 f5 48 1f c8 04    vpcmpneqq %zmm0,%zmm1,%k1
    83b2:       62 f1 fe 48 7f 93 10    vmovdqu64 %zmm2,0x10(%rbx)
    83bc:       62 f1 fe c9 6f 02       vmovdqu64 (%rdx),%zmm0{%k1}{z}
    83c2:       62 f2 f6 48 27 c9       vptestnmq %zmm1,%zmm1,%k1
    83c8:       62 f3 75 48 25 c9 ff    vpternlogd $0xff,%zmm1,%zmm1,%zmm1
...
```
They are present in relatively recent Intel CPUs (perhaps the Conda build server has one of them) but are not yet supported by AMD CPUs. By the way, @stggh, on which CPU did you try (because i7-6700 and i7-9700, from which we have your benchmarks, apparently don't support AVX-512 either)?

> I tried a new environment with Python 3.8.12 and was able to install and import pyabel 0.8.4

With some additional actions, or it just worked as is?

**Comment by stggh** [comment]
> on which CPU did you try 

Works fine for both systems:   i7-9700 CPU and i7-6700 CPU

**Comment by stggh** [comment]
In case it is useful, here is the build log, for the i7-6700 system: [gist](https://gist.github.com/stggh/75151d92c4adc8548dba8af1c14814eb)

**Comment by MikhailRyazanov** [comment]
> Works fine for both systems

Then it's really strange. Or they do have AVX-512? Or you've installed some other packages?

**Comment by stggh** [comment]
avx and avx2?

```python
lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              1
Core(s) per socket:              8
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           158
Model name:                      Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
Stepping:                        13
CPU MHz:                         2999.999
CPU max MHz:                     4700.0000
CPU min MHz:                     800.0000
BogoMIPS:                        6000.00
Virtualisation:                  VT-x
L1d cache:                       256 KiB
L1i cache:                       256 KiB
L2 cache:                        2 MiB
L3 cache:                        12 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and secc
                                 omp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitiza
                                 tion
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Mitigation; TSX disabled
Vulnerability Tsx async abort:   Mitigation; TSX disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pa
                                 t pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall 
                                 nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_
                                 good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq d
                                 tes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pd
                                 cm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes
                                  xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb
                                  invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vn
                                 mi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 sm
                                 ep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsa
                                 veopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_noti
                                 fy hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
[Gibbo:.+oodsmith/Issues]$ lscpu | grep avx
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
```

**Comment by stggh** [comment]
Null result for:
```python
/home/stg121/.local/lib/python3.9/site-packages/PyAbel-0.8.4-py3.9-linux-x86_64.egg/abel/lib
objdump -d direct.cpython-39-x86_64-linux-gnu.so | grep zmm
```

**Comment by MikhailRyazanov** [comment]
No, AVX and AVX2 are older 256-bit sets, there are supported by many CPUs. AVX-512 is a recent 512-bit extension, the flags for it should be called `avx512<something>`.

> In case it is useful, here is the build log, for the i7-6700 system

If I understand correctly, there you were building the package yourself on that machine. This should work, of course. Have you tried to installed the prebuilt Conda packages? The problem is with them.

**Comment by stggh** [comment]
> installed the prebuilt Conda packages

Ahh!  My bad. 

I will check.

**Comment by stggh** [comment]
Installs OK:
```python
conda list
# packages in environment at /home/stg121/anaconda3/envs/py39:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main 
       :                              :                             :     
pyabel                    0.8.4            py39hce5d2b2_0    conda-forge
```

Fails to run:
```python
(py39) [Gibbo:.+master/examples]$ which python
/home/stg121/anaconda3/envs/py39/bin/python
(py39) [Gibbo:.+master/examples]$ python example_O2_PES_PAD.py 
Traceback (most recent call last):
  File "/home/stg121/Software/Python/PyAbel/PyAbel-master/examples/example_O2_PES_PAD.py", line 7, in <module>
    import abel
  File "/home/stg121/.local/lib/python3.9/site-packages/PyAbel-0.8.4-py3.9-linux-x86_64.egg/abel/__init__.py", line 25, in <module>
    from . import basex
  File "/home/stg121/.local/lib/python3.9/site-packages/PyAbel-0.8.4-py3.9-linux-x86_64.egg/abel/basex.py", line 20, in <module>
    from abel.tools.polynomial import PiecewisePolynomial
  File "/home/stg121/.local/lib/python3.9/site-packages/PyAbel-0.8.4-py3.9-linux-x86_64.egg/abel/tools/__init__.py", line 6, in <module>
    from . import analytical
  File "/home/stg121/.local/lib/python3.9/site-packages/PyAbel-0.8.4-py3.9-linux-x86_64.egg/abel/tools/analytical.py", line 7, in <module>
    import scipy.interpolate
  File "/home/stg121/.local/lib/python3.9/site-packages/scipy/interpolate/__init__.py", line 166, in <module>
    from .interpolate import *
  File "/home/stg121/.local/lib/python3.9/site-packages/scipy/interpolate/interpolate.py", line 21, in <module>
    from .interpnd import _ndim_coords_from_arrays
  File "interpnd.pyx", line 1, in init scipy.interpolate.interpnd
  File "/home/stg121/.local/lib/python3.9/site-packages/scipy/spatial/__init__.py", line 96, in <module>
    from .kdtree import *
  File "/home/stg121/.local/lib/python3.9/site-packages/scipy/spatial/kdtree.py", line 5, in <module>
    from .ckdtree import cKDTree, cKDTreeNode
ImportError: /home/stg121/.local/lib/python3.9/site-packages/scipy/spatial/ckdtree.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv
```
Using `ipython` and simply `import abel`:
```python
py39) [Gibbo:.+master/examples]$ which ipython
/home/stg121/anaconda3/envs/py39/bin/ipython
(py39) [Gibbo:.+master/examples]$ ipython
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.29.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import abel
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-46961e2d8939> in <module>
----> 1 import abel

~/.local/lib/python3.9/site-packages/PyAbel-0.8.4-py3.9-linux-x86_64.egg/abel/__init__.py in <module>
     23 filterwarnings('default', r'^abel\.', category=DeprecationWarning)
     24 
---> 25 from . import basex
     26 from . import benchmark
     27 from . import dasch

~/.local/lib/python3.9/site-packages/PyAbel-0.8.4-py3.9-linux-x86_64.egg/abel/basex.py in <module>
     18 from scipy.linalg import inv
     19 
---> 20 from abel.tools.polynomial import PiecewisePolynomial
     21 
     22 from ._version import __version__

~/.local/lib/python3.9/site-packages/PyAbel-0.8.4-py3.9-linux-x86_64.egg/abel/tools/__init__.py in <module>
      4 from __future__ import unicode_literals
      5 
----> 6 from . import analytical
      7 from . import center
      8 from . import circularize

~/.local/lib/python3.9/site-packages/PyAbel-0.8.4-py3.9-linux-x86_64.egg/abel/tools/analytical.py in <module>
      5 import abel
      6 import scipy.constants as const
----> 7 import scipy.interpolate
      8 
      9 # This file includes functions that have a known analytical Abel transform.

~/.local/lib/python3.9/site-packages/scipy/interpolate/__init__.py in <module>
    164 (should not be used in new code).
    165 """
--> 166 from .interpolate import *
    167 from .fitpack import *
    168 

~/.local/lib/python3.9/site-packages/scipy/interpolate/interpolate.py in <module>
     19 from . import _ppoly
     20 from .fitpack2 import RectBivariateSpline
---> 21 from .interpnd import _ndim_coords_from_arrays
     22 from ._bsplines import make_interp_spline, BSpline
     23 

interpnd.pyx in init scipy.interpolate.interpnd()

~/.local/lib/python3.9/site-packages/scipy/spatial/__init__.py in <module>
     94 """
     95 
---> 96 from .kdtree import *
     97 from .ckdtree import *
     98 from .qhull import *

~/.local/lib/python3.9/site-packages/scipy/spatial/kdtree.py in <module>
      3 import numpy as np
      4 import warnings
----> 5 from .ckdtree import cKDTree, cKDTreeNode
      6 
      7 __all__ = ['minkowski_distance_p', 'minkowski_distance',

ImportError: /home/stg121/.local/lib/python3.9/site-packages/scipy/spatial/ckdtree.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv

```

**Comment by stggh** [comment]
Hmm, seems to be a separate problem, an overlap with the default installation.

**Comment by rth** [comment]
I'm mostly sure the problem is the `'-march=native'` flag,
https://github.com/PyAbel/PyAbel/blob/ab03e247fe9fef22a266648f027fc14b31b45458/setup.py#L41
as it would result in a non portable binary, that will use the same CPU features as the one used for the build. We should remove it.

**Comment by rth** [comment]
OK, I did already say the same thing above. I was sure I did, but couldn't find where :)

**Comment by MikhailRyazanov** [comment]
@stggh, since you have some troubles installing the Conda package but can build your own, could you please in the meantime test how much this "native" actually helps in terms of speed on your machines? Because on my laptop it surprisingly makes the code _slower_, while replacing `-O2` by `-Ofast` (which should be fine for our purposes) makes it noticeably faster:
```
=== Forward Abel transform ====================================
Options             n = 257     n = 513    n = 1025    n = 2047
---------------------------------------------------------------
-O2 -march=native       4.2        32.7       239.5      2055.4
-O2                     3.3        24.2       164.1      1475.4
-Ofast                  2.6        17.6       109.8      1069.3

=== Inverse Abel transform ====================================
Options             n = 257     n = 513    n = 1025    n = 2047
---------------------------------------------------------------
-O2 -march=native       5.0        35.7       254.9      2166.2
-O2                     4.3        27.4       179.4      1587.5
-Ofast                  3.6        20.6       125.5      1181.4
```

**Comment by stggh** [comment]
> an overlap with the default installation.

I had to resort to using the `conda` installation:

```python
(base) [Gibbo:/home/stg121]$ conda install pyabel
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/stg121/anaconda3

  added / updated specs:
    - pyabel


The following NEW packages will be INSTALLED:

  pyabel             conda-forge/linux-64::pyabel-0.8.4-py39hce5d2b2_0
  python_abi         conda-forge/linux-64::python_abi-3.9-2_cp39


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

The import fails, without any helpful error messages:
```python
(base) [Gibbo:/home/stg121]$ python
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import abel
Illegal instruction (core dumped)
```
> test how much this "native" actually helps in terms of speed on your machines? 

Back to the installed version, re-building each optimized version

```python
=== Forward Abel transform ====================================

Method              n = 257     n = 513    n = 1025    n = 2047
---------------------------------------------------------------
-O2 -march=native   3.7        29.6       202.3      1669.7
-O2                 3.4        26.7       199.6      1537.3
-Ofast              2.5        17.7       118.7       942.4


=== Inverse Abel transform ====================================

Method              n = 257     n = 513    n = 1025    n = 2047
---------------------------------------------------------------
-O2 -march=native   4.0        30.7       211.7      1697.4
-O2                 3.8        28.1       212.7      1577.1
-Ofast              2.7        19.2       130.2       980.3
```
Yes, code is is lower with `-native`, but not by much. `-Ofast` makes a big difference.

```python
i7-9700 CPU @ 3.00GHz
[Gibbo:/home/stg121]$ gcc --version
gcc (Ubuntu 11.2.0-7ubuntu2) 11.2.0
```

Using cpu-boost for max frequency 4.7GHz,  tends to thermally throttle the system for large jobs, okay for this test:
```python
CPU max MHz:                     4700.0000
=== Forward Abel transform ====================================

Method              n = 257     n = 513    n = 1025    n = 2047
---------------------------------------------------------------
-Ofast                1.7        11.8        76.8       570.0


=== Inverse Abel transform ====================================

Method              n = 257     n = 513    n = 1025    n = 2047
---------------------------------------------------------------
-Ofast                2.0        13.1        83.6       607.6
```

**Comment by MikhailRyazanov** [comment]
Thanks, @stggh! The fact that the precompiled package fails with “Illegal instruction” on your system supports @rth's idea about `-march=native`. And I'm somewhat surprised that `-march=native` slows the code down for you as well — I could guess that my mobile CPU has some trade-offs and while implementing extended instruction sets tries to do so more power-efficiently than faster, but seeing the same effect, although much weaker, even on a high-end CPU is really strange. Perhaps GCC optimization is just poorly tuned for such less common cases...
I'm wondering whether we can find somewhere a modern CPU supporting AVX-512 to test whether `-march=native` helps at least there.

But overall, I think that replacing current flags with `-Ofast` would be the best choice, since it should not only make the Conda packages usable, but also make `direct C` faster for most (if not all) users.

**Comment by stggh** [comment]
For whatever reason, there is a small variation from the previous timings. Repeated tonight:
```
=== Forward Abel transform ====================================

Method              n = 257     n = 513    n = 1025    n = 2047
-----------------------------------------------------------------------------
-O2 -march=native   3.5       27.6       203.7      1546.2
-O2                  3.4       27.0      199.0       1532.6
-Ofast               2.6       16.2       111.8        852.5

=== Inverse Abel transform ====================================

Method              n = 257     n = 513    n = 1025    n = 2047
-----------------------------------------------------------------------------
-O2 -march=native  3.9        28.9       221.1      1583.4
-O2                3.8        28.5       213.7      1563.0
-Ofast             2.9        17.2       123.5       884.3
```

As you state not much difference between -O2 -march=native, and -O2. 

> `-Ofast` would be the best choice

I agree. Do it!

**Comment by DanHickstein** [comment]
Yeah, even if -0fast was slower, it would still be worth it. We should prioritize making direct-C work easily on all systems. If users really want a fast reliable transform, they will likely be looking elsewhere anyway. Thanks for getting this sorted out!

**Comment by MikhailRyazanov** [comment]
OK, I've merged #331, which hopefully should solve the problem as soon as a new version is released. Let's keep this issue open until then as a reminder to confirm that new conda packages work properly.

**Comment by MikhailRyazanov** [comment]
We have finally released a new version, v0.8.5, and the conda package for it are now available.
@bwohlberg, @oobie2142, @stggh, could you please try it and report whether the problem is solved?

**Comment by bwohlberg** [comment]
The new conda package seems to resolve the original problem; I can now import the `abel` module without any error.

There is another problem, though, in the failure of test `test_dasch_deconvolution_array_sources`:
```
$ pytest --pyargs abel
============================= test session starts ==============================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
```
...
```
tests/test_dasch_methods.py ..F..                                        [ 20%]
```
...
```
=================================== FAILURES ===================================
____________________ test_dasch_deconvolution_array_sources ____________________

    def test_dasch_deconvolution_array_sources():
        im = abel.tools.analytical.SampleImage(101).image
        q = abel.tools.symmetry.get_image_quadrants(im)[0]
    
        # clean up any old deconvolution array files
        fn = 'three_point_basis_{}.npy'.format(q.shape[0])
        if os.path.exists(fn):
            os.system('rm {}'.format(fn))
    
        gb = abel.dasch.three_point_transform(q)
>       np.testing.assert_equal(abel.dasch._source, 'generated')
E       AssertionError: 
E       Items are not equal:
E        ACTUAL: 'file'
E        DESIRED: 'generated'
```

**Comment by MikhailRyazanov** [comment]
Thanks, @bwohlberg.

I guess that this new *test* error is caused by changing the default location of basis-set files. I can reproduce it locally without conda. So could you please create a separate issue about it, so that we can discuss it there and close this one about conda packages?

**Comment by bwohlberg** [comment]
Done: see #335.

**Comment by MikhailRyazanov** [comment]
I assume, the problem is now solved for everyone... If not, please reopen.
